function esc(s) { return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
export function htmlReport(result) {
    const counts = ['critical', 'error', 'warning', 'info'].map((s) => [s, result.findings.filter((f) => f.severity === s).length]);
    const findingRows = result.findings.map((f) => `<tr><td><span class="pill ${esc(f.severity)}">${esc(f.severity)}</span></td><td><code>${esc(f.ruleId)}</code></td><td>${esc(f.message)}</td><td>${esc(f.location ?? '')}</td></tr>`).join('');
    const trustRows = result.trust.map((t) => `<tr><td><code>${esc(t.identifier)}</code></td><td>${esc(t.publisher ?? '')}</td><td>${t.score}</td><td>${t.publisherMatchesSource ? '✓' : '✗'}</td><td>${t.identityMatchesPublisher === undefined ? '—' : t.identityMatchesPublisher ? '✓' : '✗'}</td><td>${t.signaturePresent ? 'yes' : 'no'}</td></tr>`).join('');
    const surfaces = 'mcpSurfaces' in result ? result.mcpSurfaces : [];
    const mcpRows = surfaces.flatMap((s) => s.tools.length
        ? s.tools.map((t) => `<tr><td><code>${esc(s.identifier)}</code></td><td><code>${esc(t.name)}</code></td><td><code>${esc(t.toolSha256.slice(0, 16))}…</code></td><td><code>${esc(s.endpoint)}</code></td></tr>`)
        : [`<tr><td><code>${esc(s.identifier)}</code></td><td>—</td><td>—</td><td><code>${esc(s.endpoint)}</code></td></tr>`]).join('');
    const mcpToolCount = surfaces.reduce((n, s) => n + s.tools.length, 0);
    return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>CatalogLock Report</title><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#080b12;color:#e7edf7}body{margin:0}.wrap{max-width:1200px;margin:auto;padding:40px 24px}.hero{border:1px solid #24304a;background:linear-gradient(135deg,#101726,#0b101a);border-radius:18px;padding:28px}h1{margin:0 0 8px;font-size:38px}.muted{color:#9ba9bd}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:20px 0}.card{background:#101624;border:1px solid #202b42;border-radius:14px;padding:18px}.num{font-size:30px;font-weight:800}table{width:100%;border-collapse:collapse;background:#0d1320;border:1px solid #202b42;border-radius:12px;overflow:hidden}th,td{padding:12px;border-bottom:1px solid #1e293b;text-align:left;vertical-align:top}th{color:#9fb0c8;font-size:12px;text-transform:uppercase;letter-spacing:.08em}code{color:#b8c9ff}.pill{font-weight:700;text-transform:uppercase;font-size:11px}.critical{color:#ff6b7a}.error{color:#ff9a62}.warning{color:#ffd166}.info{color:#7bdff2}section{margin-top:30px}a{color:#9db7ff}</style></head><body><div class="wrap"><div class="hero"><h1>🔒 CatalogLock</h1><div class="muted">ARD + MCP supply-chain report for ${esc(result.root)}</div><div class="grid">${counts.map(([s, n]) => `<div class="card"><div class="num ${s}">${n}</div><div class="muted">${s}</div></div>`).join('')}<div class="card"><div class="num">${result.catalogs.length}</div><div class="muted">catalogs</div></div><div class="card"><div class="num">${result.trust.length}</div><div class="muted">resources</div></div><div class="card"><div class="num">${surfaces.length}</div><div class="muted">MCP surfaces</div></div><div class="card"><div class="num">${mcpToolCount}</div><div class="muted">MCP tools locked</div></div></div></div><section><h2>Findings</h2><table><thead><tr><th>Severity</th><th>Rule</th><th>Message</th><th>Location</th></tr></thead><tbody>${findingRows || '<tr><td colspan="4">No findings.</td></tr>'}</tbody></table></section><section><h2>Live MCP tool surfaces</h2><table><thead><tr><th>Resource</th><th>Tool</th><th>Definition hash</th><th>Endpoint</th></tr></thead><tbody>${mcpRows || '<tr><td colspan="4">No public MCP tool surfaces locked.</td></tr>'}</tbody></table></section><section><h2>Trust graph</h2><table><thead><tr><th>Resource</th><th>Publisher</th><th>Score</th><th>Source bound</th><th>Identity bound</th><th>Signature</th></tr></thead><tbody>${trustRows || '<tr><td colspan="6">No resources.</td></tr>'}</tbody></table></section></div></body></html>`;
}
