import test from 'node:test';
import assert from 'node:assert/strict';
import { DEFAULT_POLICY, mergePolicy, policyFingerprint, severityRank } from '../src/policy.js';

test('secure defaults use ARD v0.91 and MCP 2026-07-28 posture',()=>{const p=mergePolicy();assert.equal(p.allowHttp,false);assert.equal(p.inspectMcpPrimitives,true);assert.equal(p.inspectMcpDiscover,true);assert.equal(p.mcpProtocolVersion,'2026-07-28');assert.equal(p.requireVerifiedTrust,false);});
test('legacy inspectMcpTools alias disables primitives',()=>assert.equal(mergePolicy({inspectMcpTools:false}).inspectMcpPrimitives,false));
test('explicit inspectMcpPrimitives wins over legacy alias',()=>assert.equal(mergePolicy({inspectMcpTools:false,inspectMcpPrimitives:true}).inspectMcpPrimitives,true));
test('policy fingerprint changes when policy changes',()=>assert.notEqual(policyFingerprint(DEFAULT_POLICY),policyFingerprint({...DEFAULT_POLICY,maxDepth:3})));
test('severity ranks critical highest',()=>assert.ok(severityRank('critical')>severityRank('error')&&severityRank('error')>severityRank('warning')));
test('rejects invalid depth',()=>assert.throws(()=>mergePolicy({maxDepth:99}),/maxDepth/));
test('rejects invalid MCP page bound',()=>assert.throws(()=>mergePolicy({maxMcpPages:0}),/maxMcpPages/));
test('rejects invalid MCP item bound',()=>assert.throws(()=>mergePolicy({maxMcpItems:0}),/maxMcpItems/));
test('rejects non-version MCP string',()=>assert.throws(()=>mergePolicy({mcpProtocolVersion:'latest'}),/mcpProtocolVersion/));
test('rejects duplicate MCP profile names',()=>assert.throws(()=>mergePolicy({mcpProfiles:[{name:'x',clientCapabilities:{}},{name:'x',clientCapabilities:{}}]}),/duplicate/));
test('rejects protected HTTP headers in MCP profile',()=>assert.throws(()=>mergePolicy({mcpProfiles:[{name:'x',clientCapabilities:{},headersFromEnv:{'Mcp-Method':'TOKEN'}}]}),/forbidden header/));
test('rejects invalid secret environment names',()=>assert.throws(()=>mergePolicy({mcpProfiles:[{name:'x',clientCapabilities:{},headersFromEnv:{Authorization:'bad-name'}}]}),/environment variable/));
test('rejects extension probes without explicit readOnly true',()=>assert.throws(()=>mergePolicy({mcpExtensionProbes:[{method:'acme/status',readOnly:false as true}]}),/readOnly/));
test('rejects tools/call probe',()=>assert.throws(()=>mergePolicy({mcpExtensionProbes:[{method:'tools/call',readOnly:true}]}),/not safely read-only/));
test('rejects mutation-looking custom probe',()=>assert.throws(()=>mergePolicy({mcpExtensionProbes:[{method:'acme/delete',readOnly:true}]}),/not safely read-only/));
test('accepts namespaced read-only custom probe',()=>assert.equal(mergePolicy({mcpExtensionProbes:[{method:'acme/status',readOnly:true}]}).mcpExtensionProbes.length,1));
