import test from 'node:test';
import assert from 'node:assert/strict';
import { ARD_CONTEXT_SHA256, findArdLink, resolveCatalogs } from '../src/resolver.js';
import type { FetchResult } from '../src/types.js';

const ard='https://example.com/.well-known/ard.json';
const legacy='https://example.com/.well-known/ai-catalog.json';
const entry={identifier:'urn:air:example.com:agent:a',displayName:'A',type:'application/a2a-agent-card+json',url:'https://api.example.com/a',representativeQueries:['do a','help a']};
const manifest={entries:[entry]};
const response=(url:string,status:number,body:unknown,contentType='application/json'):FetchResult=>({url,status,body:typeof body==='string'?body:JSON.stringify(body),contentType});

test('findArdLink finds rel ard regardless attribute order',()=>assert.equal(findArdLink('<link href="/custom/ard.json" type="application/json" rel="alternate ard">','https://example.com/'),'https://example.com/custom/ard.json'));
test('canonical /.well-known/ard.json is preferred',async()=>{const seen:string[]=[];const r=await resolveCatalogs('example.com',{fetcher:async url=>{seen.push(url);return response(url,url===ard?200:404,manifest)}});assert.equal(r.root,ard);assert.equal(r.rootSourceKind,'ard');assert.equal(seen[0],ard);});
test('legacy ai-catalog path is fallback with warning',async()=>{const r=await resolveCatalogs('example.com',{fetcher:async url=>response(url,url===legacy?200:404,manifest)});assert.equal(r.rootSourceKind,'legacy-ai-catalog');assert.ok(r.findings.some(f=>f.ruleId==='compat/ai-catalog-json'));});
test('legacy fallback can be disabled',async()=>{const seen:string[]=[];const r=await resolveCatalogs('example.com',{policy:{allowCompatibilityAiCatalogJson:false},fetcher:async url=>{seen.push(url);return response(url,404,{})}});assert.equal(r.catalogs.length,0);assert.ok(!seen.includes(legacy));});
test('HTML rel=ard is additional fallback after well-known failure',async()=>{const custom='https://example.com/custom/manifest.json';const f=async(url:string)=>url===ard||url===legacy?response(url,404,{}):url==='https://example.com/'?response(url,200,'<html><head><link rel="ard" href="/custom/manifest.json"></head></html>','text/html'):response(url,url===custom?200:404,manifest);const r=await resolveCatalogs('example.com',{fetcher:f});assert.equal(r.root,custom);assert.equal(r.rootSourceKind,'rel-ard');});
test('explicit HTML URL follows rel=ard',async()=>{const page='https://example.com/discovery';const custom='https://example.com/ard.json';const r=await resolveCatalogs(page,{fetcher:async url=>url===page?response(url,200,'<link rel="ard" href="/ard.json">','text/html'):response(url,200,manifest)});assert.equal(r.root,custom);assert.equal(r.rootSourceKind,'rel-ard');});
test('ARD context fingerprint is always locked',async()=>{const r=await resolveCatalogs('example.com',{fetcher:async url=>response(url,url===ard?200:404,manifest)});assert.equal(r.ardContextSha256,ARD_CONTEXT_SHA256);assert.match(r.ardContextSha256,/^[a-f0-9]{64}$/);});
test('nested catalog is followed once',async()=>{const nested='https://sub.example.com/catalog.json';const root={entries:[{identifier:'urn:air:example.com:catalog:sub',displayName:'Sub',type:'application/ai-catalog+json',url:nested,representativeQueries:['sub one','sub two']}]};const f=async(url:string)=>response(url,url===ard||url===nested?200:404,url===ard?root:manifest);const r=await resolveCatalogs('example.com',{fetcher:f});assert.equal(r.catalogs.length,2);});
test('maxDepth prevents nested fetch',async()=>{const nested='https://sub.example.com/catalog.json';const root={entries:[{identifier:'urn:air:example.com:catalog:sub',displayName:'Sub',type:'application/ai-catalog+json',url:nested,representativeQueries:['sub one','sub two']}]};const r=await resolveCatalogs('example.com',{policy:{maxDepth:0},fetcher:async url=>response(url,url===ard?200:404,root)});assert.equal(r.catalogs.length,1);assert.ok(r.findings.some(f=>f.ruleId==='limits/depth'));});
test('identifier collision across entry sources is critical',async()=>{const nested='https://sub.example.com/catalog.json';const root={entries:[{identifier:'urn:air:example.com:catalog:sub',displayName:'Sub',type:'application/ai-catalog+json',url:nested,representativeQueries:['sub one','sub two']}]};const nestedManifest={entries:[{...root.entries[0],displayName:'Duplicate',type:'application/a2a-agent-card+json',url:'https://api.example.com/x'}]};const r=await resolveCatalogs('example.com',{fetcher:async url=>response(url,url===ard||url===nested?200:404,url===ard?root:nestedManifest)});assert.ok(r.findings.some(f=>f.ruleId==='authority/identifier-collision'&&f.severity==='critical'));});
test('unexpected nested HTML is rejected',async()=>{const nested='https://sub.example.com/catalog.json';const root={entries:[{identifier:'urn:air:example.com:catalog:sub',displayName:'Sub',type:'application/ai-catalog+json',url:nested,representativeQueries:['sub one','sub two']}]};const r=await resolveCatalogs('example.com',{fetcher:async url=>url===ard?response(url,200,root):response(url,200,'<html>x</html>','text/html')});assert.ok(r.findings.some(f=>f.ruleId==='parse/unexpected-html'));});
test('publisher authority mismatch is surfaced during resolution',async()=>{const bad={entries:[{...entry,identifier:'urn:air:other.example:agent:a'}]};const r=await resolveCatalogs('example.com',{fetcher:async url=>response(url,url===ard?200:404,bad)});assert.ok(r.findings.some(f=>f.ruleId==='authority/publisher-source'&&f.severity==='critical'));});
