import test from 'node:test';
import assert from 'node:assert/strict';
import { validateCatalog } from '../src/schema.js';
import { mergePolicy } from '../src/policy.js';
const p=mergePolicy();
const entry={identifier:'urn:air:example.com:agent:x',displayName:'X',type:'application/a2a-agent-card+json',url:'https://api.example.com/x',representativeQueries:['help with x','use x']};
const good={entries:[entry]};

test('accepts minimal ARD v0.91 manifest without legacy host/specVersion',()=>{const r=validateCatalog(good,'https://example.com/.well-known/ard.json',p);assert.ok(r.catalog);assert.equal(r.findings.length,0);});
test('accepts transport-defined root properties',()=>assert.ok(validateCatalog({...good,foo:'bar'},'x',p).catalog));
test('rejects non-object manifest',()=>assert.equal(validateCatalog([], 'x',p).findings[0]?.severity,'critical'));
test('requires entries array',()=>assert.ok(validateCatalog({},'x',p).findings.some(f=>f.ruleId==='schema/entries')));
test('rejects malformed urn:air identifier',()=>{const r=validateCatalog({entries:[{...entry,identifier:'agent:x'}]},'x',p);assert.ok(r.findings.some(f=>f.ruleId==='schema/identifier'));});
test('detects duplicate identifiers',()=>assert.ok(validateCatalog({entries:[entry,entry]},'x',p).findings.some(f=>f.ruleId==='schema/duplicate-identifier')));
test('requires exactly one of url/data',()=>assert.ok(validateCatalog({entries:[{...entry,data:{x:1}}]},'x',p).findings.some(f=>f.ruleId==='schema/url-xor-data')));
test('inline data satisfies value-or-reference rule',()=>{const {url,...e}=entry;assert.ok(validateCatalog({entries:[{...e,data:{x:1}}]},'x',p).catalog);});
test('flags cleartext resource URL',()=>assert.ok(validateCatalog({entries:[{...entry,url:'http://example.com/x'}]},'x',p).findings.some(f=>f.ruleId==='transport/entry-https')));
test('rejects credentials in resource URL',()=>assert.ok(validateCatalog({entries:[{...entry,url:'https://u:p@example.com/x'}]},'x',p).findings.some(f=>f.ruleId==='transport/url-credentials')));
test('JSON-LD @id must match identifier',()=>assert.ok(validateCatalog({entries:[{...entry,'@id':'urn:air:example.com:agent:y'}]},'x',p).findings.some(f=>f.ruleId==='schema/jsonld-id-mismatch')));
test('JSON-LD context accepts URI/object/array',()=>{for(const ctx of ['https://x.test/c',{'x':'https://x/'},['https://x.test/c']])assert.ok(validateCatalog({'@context':ctx,entries:[entry]},'x',p).catalog);});
test('invalid JSON-LD context is rejected',()=>assert.ok(validateCatalog({'@context':4,entries:[entry]},'x',p).findings.some(f=>f.ruleId==='schema/jsonld-context')));
test('missing representativeQueries is warning not invalidation',()=>{const {representativeQueries,...e}=entry;const r=validateCatalog({entries:[e]},'x',p);assert.ok(r.catalog);assert.ok(r.findings.some(f=>f.ruleId==='discovery/representative-queries'&&f.severity==='warning'));});
test('representativeQueries outside 2 to 5 is warning',()=>assert.ok(validateCatalog({entries:[{...entry,representativeQueries:['one']}]},'x',p).findings.some(f=>f.ruleId==='discovery/representative-queries-count')));
test('trustManifest requires identity when present',()=>assert.ok(validateCatalog({entries:[{...entry,trustManifest:{signature:'x'}}]},'x',p).findings.some(f=>f.ruleId==='schema/trust-identity')));
test('metadata values are limited to scalar JSON values',()=>assert.ok(validateCatalog({entries:[{...entry,metadata:{bad:{x:1} as any}}]},'x',p).findings.some(f=>f.ruleId==='schema/metadata')));
test('legacy collections root is warned',()=>assert.ok(validateCatalog({...good,collections:[]},'x',p).findings.some(f=>f.ruleId==='compat/collections')));
test('entry count bound is enforced',()=>assert.ok(validateCatalog({entries:[entry,{...entry,identifier:'urn:air:example.com:agent:y'}]},'x',mergePolicy({maxEntriesPerCatalog:1})).findings.some(f=>f.ruleId==='limits/entry-count')));
