import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign as cryptoSign } from 'node:crypto';
import { assessEntryTrust, hostWithin, identityHost, publisherFromIdentifier } from '../src/trust.js';
import { mergePolicy } from '../src/policy.js';
import { canonicalJson, sha256 } from '../src/canonical.js';
import type { CatalogEntry, FetchResult, TrustManifest } from '../src/types.js';

const source='https://example.com/.well-known/ard.json';
const base:CatalogEntry={identifier:'urn:air:example.com:agent:x',displayName:'X',type:'application/a2a-agent-card+json',url:'https://api.example.com/x',representativeQueries:['x one','x two']};
const emptyFetcher=async(url:string):Promise<FetchResult>=>({url,status:404,body:''});
const b64url=(v:Buffer|string)=>Buffer.from(v).toString('base64url');

test('extracts publisher from urn:air',()=>assert.equal(publisherFromIdentifier(base.identifier),'example.com'));
test('hostWithin accepts subdomains',()=>assert.equal(hostWithin('api.example.com','example.com'),true));
test('hostWithin rejects suffix trick',()=>assert.equal(hostWithin('example.com.evil.test','example.com'),false));
test('identityHost understands did:web',()=>assert.equal(identityHost('did:web:example.com:user:alice'),'example.com'));
test('identityHost understands SPIFFE',()=>assert.equal(identityHost('spiffe://example.com/service/a'),'example.com'));
test('publisher/source mismatch is critical',async()=>{const r=await assessEntryTrust(base,'https://evil.test/.well-known/ard.json',mergePolicy(),emptyFetcher);assert.ok(r.findings.some(f=>f.ruleId==='authority/publisher-source'&&f.severity==='critical'));});
test('publisher mismatch enforcement can be disabled',async()=>{const r=await assessEntryTrust(base,'https://mirror.test/.well-known/ard.json',mergePolicy({requirePublisherMatch:false}),emptyFetcher);assert.ok(!r.findings.some(f=>f.ruleId==='authority/publisher-source'));assert.equal(r.assessment.publisherMatchesSource,false);});
test('no manifest has absent trust state',async()=>{const r=await assessEntryTrust(base,source,mergePolicy(),emptyFetcher);assert.equal(r.assessment.state,'absent');assert.equal(r.assessment.score,55);});
test('aligned identity-only manifest is present-unverified',async()=>{const r=await assessEntryTrust({...base,trustManifest:{identity:'https://id.example.com'}},source,mergePolicy(),emptyFetcher);assert.equal(r.assessment.state,'present-unverified');assert.equal(r.assessment.identityMatchesPublisher,true);});
test('identity mismatch invalidates trust',async()=>{const r=await assessEntryTrust({...base,trustManifest:{identity:'https://evil.test'}},source,mergePolicy(),emptyFetcher);assert.equal(r.assessment.state,'invalid');assert.ok(r.findings.some(f=>f.ruleId==='authority/trust-identity'));});
test('requireVerifiedTrust fails absent trust',async()=>{const r=await assessEntryTrust(base,source,mergePolicy({requireVerifiedTrust:true}),emptyFetcher);assert.ok(r.findings.some(f=>f.ruleId==='trust/required-verification'&&f.severity==='error'));});
test('matching binary attestation digest verifies trust byte-accurately',async()=>{const bytes=Buffer.from([0,255,1,254,2]);const digest=sha256(bytes);const entry={...base,trustManifest:{identity:'https://example.com',attestations:[{type:'binary',uri:'https://example.com/evidence.bin',digest:`sha256:${digest}`}]} };const fetcher=async(url:string):Promise<FetchResult>=>({url,status:200,body:bytes.toString('utf8'),bodyBytes:bytes});const r=await assessEntryTrust(entry,source,mergePolicy(),fetcher);assert.equal(r.assessment.state,'verified');assert.ok(r.assessment.verifiedEvidenceDigests.includes(`attestation:${digest}`));});
test('attestation digest mismatch invalidates trust',async()=>{const entry={...base,trustManifest:{identity:'https://example.com',attestations:[{type:'x',uri:'https://example.com/e',digest:'0'.repeat(64)}]}};const r=await assessEntryTrust(entry,source,mergePolicy(),async url=>({url,status:200,body:'different'}));assert.equal(r.assessment.state,'invalid');assert.ok(r.findings.some(f=>f.ruleId==='trust/attestation-digest'));});
test('HTTPS provenance digest can verify trust',async()=>{const body='source-build';const digest=sha256(body);const entry={...base,trustManifest:{identity:'https://example.com',provenance:[{relation:'builtFrom',sourceId:'https://example.com/source',sourceDigest:digest}]}};const r=await assessEntryTrust(entry,source,mergePolicy(),async url=>({url,status:200,body}));assert.equal(r.assessment.state,'verified');assert.ok(r.assessment.verifiedEvidenceDigests.includes(`provenance:${digest}`));});
test('pluggable framework verifier can establish verified state',async()=>{const entry={...base,trustManifest:{identity:'https://example.com',trustSchema:{identifier:'custom'}}};const r=await assessEntryTrust(entry,source,mergePolicy(),emptyFetcher,[async()=>({state:'verified',verifiedEvidenceDigests:['plugin:ok']})]);assert.equal(r.assessment.state,'verified');assert.ok(r.assessment.verifiedEvidenceDigests.includes('plugin:ok'));});
test('unrecognised signature framework is unsupported rather than trusted',async()=>{const entry={...base,trustManifest:{identity:'https://example.com',signature:'a.b.c',trustSchema:{identifier:'other'}}};const r=await assessEntryTrust(entry,source,mergePolicy(),emptyFetcher);assert.equal(r.assessment.state,'unsupported');assert.ok(r.findings.some(f=>f.ruleId==='trust/signature-unverified'));});
test('CatalogLock canonical detached RS256 JWS verifies with JWKS',async()=>{
  const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
  const jwk=publicKey.export({format:'jwk'}); (jwk as any).kid='k1';
  const manifest:TrustManifest={identity:'https://example.com',jwksUri:'https://example.com/jwks',trustSchema:{identifier:'cataloglock',verificationMethods:['cataloglock:canonical-jws']}};
  const protected64=b64url(JSON.stringify({alg:'RS256',kid:'k1'}));
  const payload64=b64url(canonicalJson(manifest));
  const sig=cryptoSign('RSA-SHA256',Buffer.from(`${protected64}.${payload64}`),privateKey);
  manifest.signature=`${protected64}..${b64url(sig)}`;
  const entry={...base,trustManifest:manifest};
  const r=await assessEntryTrust(entry,source,mergePolicy(),async url=>({url,status:200,body:JSON.stringify({keys:[jwk]})}));
  assert.equal(r.assessment.state,'verified');assert.ok(r.assessment.verifiedEvidenceDigests.some(x=>x.startsWith('jws:')));
});
test('canonical JWS rejects algorithms outside policy',async()=>{const manifest:TrustManifest={identity:'https://example.com',signature:`${b64url(JSON.stringify({alg:'none'}))}..`,trustSchema:{verificationMethods:['cataloglock:canonical-jws']}};const r=await assessEntryTrust({...base,trustManifest:manifest},source,mergePolicy(),emptyFetcher);assert.equal(r.assessment.state,'invalid');});
